package hw1_single_inventory;

public enum ErrorStates {
	NO_ERROR,
	INVALID_DATE,
	WRONG_ARGUMENT_COUNT,
	CANNOT_BUY_BEFORE_ADD,
	CANNOT_SELL_BEFORE_ADD,
	INVALID_QUANTITY,
	CANNOT_SELL_QUANTITY_MORE_THAN_STOCK,
	FILE_NOT_FOUND,
	DUPLICATE_ENTRY,
	UNKNOWN_COMMAND,
	TOTAL_COMMANDS
}
